/**
 * Role Based Access Control
 * The API for Role Based Access Control.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Access from './Access';
import ListPagination from './ListPagination';
import PaginationLinks from './PaginationLinks';
import PaginationMeta from './PaginationMeta';

/**
 * The AccessPagination model module.
 * @module model/AccessPagination
 * @version 1.0.0
 */
class AccessPagination {
    /**
     * Constructs a new <code>AccessPagination</code>.
     * @alias module:model/AccessPagination
     * @extends module:model/ListPagination
     * @implements module:model/ListPagination
     * @param data {} 
     */
    constructor(data) { 
        ListPagination.initialize(this);
        AccessPagination.initialize(this, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data) { 
        obj['data'] = data;
    }

    /**
     * Constructs a <code>AccessPagination</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccessPagination} obj Optional instance to populate.
     * @return {module:model/AccessPagination} The populated <code>AccessPagination</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccessPagination();
            ListPagination.constructFromObject(data, obj);
            ListPagination.constructFromObject(data, obj);

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Access]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Access>} data
 */
AccessPagination.prototype['data'] = undefined;


// Implement ListPagination interface:
/**
 * @member {module:model/PaginationMeta} meta
 */
ListPagination.prototype['meta'] = undefined;
/**
 * @member {module:model/PaginationLinks} links
 */
ListPagination.prototype['links'] = undefined;




export default AccessPagination;

