/**
 * Role Based Access Control
 * The API for Role Based Access Control.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResourceDefinition from './ResourceDefinition';

/**
 * The Access model module.
 * @module model/Access
 * @version 1.0.0
 */
class Access {
    /**
     * Constructs a new <code>Access</code>.
     * @alias module:model/Access
     * @param permission {String} 
     * @param resourceDefinition {Array.<module:model/ResourceDefinition>} 
     */
    constructor(permission, resourceDefinition) { 
        
        Access.initialize(this, permission, resourceDefinition);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, permission, resourceDefinition) { 
        obj['permission'] = permission;
        obj['resourceDefinition'] = resourceDefinition;
    }

    /**
     * Constructs a <code>Access</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Access} obj Optional instance to populate.
     * @return {module:model/Access} The populated <code>Access</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Access();

            if (data.hasOwnProperty('permission')) {
                obj['permission'] = ApiClient.convertToType(data['permission'], 'String');
            }
            if (data.hasOwnProperty('resourceDefinition')) {
                obj['resourceDefinition'] = ApiClient.convertToType(data['resourceDefinition'], [ResourceDefinition]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} permission
 */
Access.prototype['permission'] = undefined;

/**
 * @member {Array.<module:model/ResourceDefinition>} resourceDefinition
 */
Access.prototype['resourceDefinition'] = undefined;






export default Access;

