/**
 * Role Based Access Control
 * The API for Role Based Access Control.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PrincipalIn from './PrincipalIn';

/**
 * The GroupPrincipalIn model module.
 * @module model/GroupPrincipalIn
 * @version 1.0.0
 */
class GroupPrincipalIn {
    /**
     * Constructs a new <code>GroupPrincipalIn</code>.
     * @alias module:model/GroupPrincipalIn
     * @param principals {Array.<module:model/PrincipalIn>} 
     */
    constructor(principals) { 
        
        GroupPrincipalIn.initialize(this, principals);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, principals) { 
        obj['principals'] = principals;
    }

    /**
     * Constructs a <code>GroupPrincipalIn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GroupPrincipalIn} obj Optional instance to populate.
     * @return {module:model/GroupPrincipalIn} The populated <code>GroupPrincipalIn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupPrincipalIn();

            if (data.hasOwnProperty('principals')) {
                obj['principals'] = ApiClient.convertToType(data['principals'], [PrincipalIn]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/PrincipalIn>} principals
 */
GroupPrincipalIn.prototype['principals'] = undefined;






export default GroupPrincipalIn;

