/**
 * Role Based Access Control
 * The API for Role Based Access Control.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaginationLinks from './PaginationLinks';
import PaginationMeta from './PaginationMeta';

/**
 * The ListPagination model module.
 * @module model/ListPagination
 * @version 1.0.0
 */
class ListPagination {
    /**
     * Constructs a new <code>ListPagination</code>.
     * @alias module:model/ListPagination
     */
    constructor() { 
        
        ListPagination.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListPagination</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListPagination} obj Optional instance to populate.
     * @return {module:model/ListPagination} The populated <code>ListPagination</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListPagination();

            if (data.hasOwnProperty('meta')) {
                obj['meta'] = PaginationMeta.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = PaginationLinks.constructFromObject(data['links']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PaginationMeta} meta
 */
ListPagination.prototype['meta'] = undefined;

/**
 * @member {module:model/PaginationLinks} links
 */
ListPagination.prototype['links'] = undefined;






export default ListPagination;

