/**
 * Role Based Access Control
 * The API for Role Based Access Control.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PolicyIn from './PolicyIn';
import UUID from './UUID';

/**
 * The PolicyOut model module.
 * @module model/PolicyOut
 * @version 1.0.0
 */
class PolicyOut {
    /**
     * Constructs a new <code>PolicyOut</code>.
     * @alias module:model/PolicyOut
     * @extends module:model/PolicyIn
     * @implements module:model/PolicyIn
     * @implements module:model/UUID
     * @param name {} 
     * @param group {} 
     * @param roles {} 
     * @param uuid {} 
     */
    constructor(name, group, roles, uuid) { 
        PolicyIn.initialize(this, name, group, roles);UUID.initialize(this, uuid);
        PolicyOut.initialize(this, name, group, roles, uuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, group, roles, uuid) { 
    }

    /**
     * Constructs a <code>PolicyOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PolicyOut} obj Optional instance to populate.
     * @return {module:model/PolicyOut} The populated <code>PolicyOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PolicyOut();
            PolicyIn.constructFromObject(data, obj);
            PolicyIn.constructFromObject(data, obj);
            UUID.constructFromObject(data, obj);

        }
        return obj;
    }


}


// Implement PolicyIn interface:
/**
 * @member {} name
 */
PolicyIn.prototype['name'] = undefined;
/**
 * @member {} description
 */
PolicyIn.prototype['description'] = undefined;
/**
 * @member {} group
 */
PolicyIn.prototype['group'] = undefined;
/**
 * @member {} roles
 */
PolicyIn.prototype['roles'] = undefined;
// Implement UUID interface:
/**
 * @member {String} uuid
 */
UUID.prototype['uuid'] = undefined;




export default PolicyOut;

