/**
 * Role Based Access Control
 * The API for Role Based Access Control.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GroupOut from './GroupOut';
import Policy from './Policy';
import RoleOut from './RoleOut';
import UUID from './UUID';

/**
 * The PolicyExtended model module.
 * @module model/PolicyExtended
 * @version 1.0.0
 */
class PolicyExtended {
    /**
     * Constructs a new <code>PolicyExtended</code>.
     * @alias module:model/PolicyExtended
     * @extends module:model/Policy
     * @implements module:model/Policy
     * @implements module:model/UUID
     * @param name {} 
     * @param uuid {} 
     * @param group {} 
     * @param roles {} 
     */
    constructor(name, uuid, group, roles) { 
        Policy.initialize(this, name);UUID.initialize(this, uuid);
        PolicyExtended.initialize(this, name, uuid, group, roles);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, uuid, group, roles) { 
        obj['group'] = group;
        obj['roles'] = roles;
    }

    /**
     * Constructs a <code>PolicyExtended</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PolicyExtended} obj Optional instance to populate.
     * @return {module:model/PolicyExtended} The populated <code>PolicyExtended</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PolicyExtended();
            Policy.constructFromObject(data, obj);
            Policy.constructFromObject(data, obj);
            UUID.constructFromObject(data, obj);

            if (data.hasOwnProperty('group')) {
                obj['group'] = GroupOut.constructFromObject(data['group']);
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], [RoleOut]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/GroupOut} group
 */
PolicyExtended.prototype['group'] = undefined;

/**
 * @member {Array.<module:model/RoleOut>} roles
 */
PolicyExtended.prototype['roles'] = undefined;


// Implement Policy interface:
/**
 * @member {String} name
 */
Policy.prototype['name'] = undefined;
/**
 * @member {String} description
 */
Policy.prototype['description'] = undefined;
// Implement UUID interface:
/**
 * @member {String} uuid
 */
UUID.prototype['uuid'] = undefined;




export default PolicyExtended;

