/**
 * Role Based Access Control
 * The API for Role Based Access Control.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Principal model module.
 * @module model/Principal
 * @version 1.0.0
 */
class Principal {
    /**
     * Constructs a new <code>Principal</code>.
     * @alias module:model/Principal
     * @param username {String} 
     * @param email {String} 
     */
    constructor(username, email) { 
        
        Principal.initialize(this, username, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, email) { 
        obj['username'] = username;
        obj['email'] = email;
    }

    /**
     * Constructs a <code>Principal</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Principal} obj Optional instance to populate.
     * @return {module:model/Principal} The populated <code>Principal</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Principal();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('is_org_admin')) {
                obj['is_org_admin'] = ApiClient.convertToType(data['is_org_admin'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
Principal.prototype['username'] = undefined;

/**
 * @member {String} email
 */
Principal.prototype['email'] = undefined;

/**
 * @member {String} first_name
 */
Principal.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
Principal.prototype['last_name'] = undefined;

/**
 * @member {Boolean} is_org_admin
 */
Principal.prototype['is_org_admin'] = undefined;






export default Principal;

