/**
 * Role Based Access Control
 * The API for Role Based Access Control.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResourceDefinitionFilter from './ResourceDefinitionFilter';

/**
 * The ResourceDefinition model module.
 * @module model/ResourceDefinition
 * @version 1.0.0
 */
class ResourceDefinition {
    /**
     * Constructs a new <code>ResourceDefinition</code>.
     * @alias module:model/ResourceDefinition
     * @param attributeFilter {module:model/ResourceDefinitionFilter} 
     */
    constructor(attributeFilter) { 
        
        ResourceDefinition.initialize(this, attributeFilter);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, attributeFilter) { 
        obj['attributeFilter'] = attributeFilter;
    }

    /**
     * Constructs a <code>ResourceDefinition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResourceDefinition} obj Optional instance to populate.
     * @return {module:model/ResourceDefinition} The populated <code>ResourceDefinition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResourceDefinition();

            if (data.hasOwnProperty('attributeFilter')) {
                obj['attributeFilter'] = ResourceDefinitionFilter.constructFromObject(data['attributeFilter']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ResourceDefinitionFilter} attributeFilter
 */
ResourceDefinition.prototype['attributeFilter'] = undefined;






export default ResourceDefinition;

