/**
 * Role Based Access Control
 * The API for Role Based Access Control.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Role from './Role';
import UUID from './UUID';

/**
 * The RoleOut model module.
 * @module model/RoleOut
 * @version 1.0.0
 */
class RoleOut {
    /**
     * Constructs a new <code>RoleOut</code>.
     * @alias module:model/RoleOut
     * @extends module:model/Role
     * @implements module:model/Role
     * @implements module:model/UUID
     * @param name {} 
     * @param uuid {} 
     */
    constructor(name, uuid) { 
        Role.initialize(this, name);UUID.initialize(this, uuid);
        RoleOut.initialize(this, name, uuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, uuid) { 
    }

    /**
     * Constructs a <code>RoleOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RoleOut} obj Optional instance to populate.
     * @return {module:model/RoleOut} The populated <code>RoleOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RoleOut();
            Role.constructFromObject(data, obj);
            Role.constructFromObject(data, obj);
            UUID.constructFromObject(data, obj);

        }
        return obj;
    }


}


// Implement Role interface:
/**
 * @member {String} name
 */
Role.prototype['name'] = undefined;
/**
 * @member {String} description
 */
Role.prototype['description'] = undefined;
// Implement UUID interface:
/**
 * @member {String} uuid
 */
UUID.prototype['uuid'] = undefined;




export default RoleOut;

