/**
 * Role Based Access Control
 * The API for Role Based Access Control.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Access from './Access';
import Role from './Role';

/**
 * The RoleIn model module.
 * @module model/RoleIn
 * @version 1.0.0
 */
class RoleIn {
    /**
     * Constructs a new <code>RoleIn</code>.
     * @alias module:model/RoleIn
     * @extends module:model/Role
     * @implements module:model/Role
     * @param name {} 
     * @param access {} 
     */
    constructor(name, access) { 
        Role.initialize(this, name);
        RoleIn.initialize(this, name, access);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, access) { 
        obj['access'] = access;
    }

    /**
     * Constructs a <code>RoleIn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RoleIn} obj Optional instance to populate.
     * @return {module:model/RoleIn} The populated <code>RoleIn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RoleIn();
            Role.constructFromObject(data, obj);
            Role.constructFromObject(data, obj);

            if (data.hasOwnProperty('access')) {
                obj['access'] = ApiClient.convertToType(data['access'], [Access]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Access>} access
 */
RoleIn.prototype['access'] = undefined;


// Implement Role interface:
/**
 * @member {String} name
 */
Role.prototype['name'] = undefined;
/**
 * @member {String} description
 */
Role.prototype['description'] = undefined;




export default RoleIn;

