/**
 * Role Based Access Control
 * The API for Role Based Access Control.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UUID model module.
 * @module model/UUID
 * @version 1.0.0
 */
class UUID {
    /**
     * Constructs a new <code>UUID</code>.
     * @alias module:model/UUID
     * @param uuid {String} 
     */
    constructor(uuid) { 
        
        UUID.initialize(this, uuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uuid) { 
        obj['uuid'] = uuid;
    }

    /**
     * Constructs a <code>UUID</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UUID} obj Optional instance to populate.
     * @return {module:model/UUID} The populated <code>UUID</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UUID();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} uuid
 */
UUID.prototype['uuid'] = undefined;






export default UUID;

