/**
 * Role Based Access Control
 * The API for Role Based Access Control.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import PolicyExtended from '../model/PolicyExtended';
import PolicyIn from '../model/PolicyIn';
import PolicyPagination from '../model/PolicyPagination';

/**
* Policy service.
* @module api/PolicyApi
* @version 1.0.0
*/
export default class PolicyApi {

    /**
    * Constructs a new PolicyApi. 
    * @alias module:api/PolicyApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Create a policy in a tenant
     * @param {module:model/PolicyIn} policyIn Policy to create
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PolicyExtended} and HTTP response
     */
    createPoliciesWithHttpInfo(policyIn) {
      let postBody = policyIn;

      // verify the required parameter 'policyIn' is set
      if (policyIn === undefined || policyIn === null) {
        throw new Error("Missing the required parameter 'policyIn' when calling createPolicies");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic_auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PolicyExtended;

      return this.apiClient.callApi(
        '/policies/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Create a policy in a tenant
     * @param {module:model/PolicyIn} policyIn Policy to create
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PolicyExtended}
     */
    createPolicies(policyIn) {
      return this.createPoliciesWithHttpInfo(policyIn)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete a policy in the tenant
     * @param {String} uuid ID of policy to delete
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deletePolicyWithHttpInfo(uuid) {
      let postBody = null;

      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling deletePolicy");
      }


      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/policies/{uuid}/', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete a policy in the tenant
     * @param {String} uuid ID of policy to delete
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deletePolicy(uuid) {
      return this.deletePolicyWithHttpInfo(uuid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a policy in the tenant
     * @param {String} uuid ID of policy to get
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PolicyExtended} and HTTP response
     */
    getPolicyWithHttpInfo(uuid) {
      let postBody = null;

      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getPolicy");
      }


      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PolicyExtended;

      return this.apiClient.callApi(
        '/policies/{uuid}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get a policy in the tenant
     * @param {String} uuid ID of policy to get
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PolicyExtended}
     */
    getPolicy(uuid) {
      return this.getPolicyWithHttpInfo(uuid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List the policies in the tenant
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageSize Parameter for selecting the amount of data in a page. (default to 10)
     * @param {Number} opts.page Parameter for selecting the page of data. (default to 1)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PolicyPagination} and HTTP response
     */
    listPoliciesWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
        'page_size': opts['pageSize'],
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PolicyPagination;

      return this.apiClient.callApi(
        '/policies/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * List the policies in the tenant
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageSize Parameter for selecting the amount of data in a page. (default to 10)
     * @param {Number} opts.page Parameter for selecting the page of data. (default to 1)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PolicyPagination}
     */
    listPolicies(opts) {
      return this.listPoliciesWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update a policy in the tenant
     * @param {String} uuid ID of policy to update
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PolicyExtended} and HTTP response
     */
    updatePolicyWithHttpInfo(uuid) {
      let postBody = null;

      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling updatePolicy");
      }


      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PolicyExtended;

      return this.apiClient.callApi(
        '/policies/{uuid}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Update a policy in the tenant
     * @param {String} uuid ID of policy to update
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PolicyExtended}
     */
    updatePolicy(uuid) {
      return this.updatePolicyWithHttpInfo(uuid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
