/**
 * Role Based Access Control
 * The API for Role Based Access Control.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RoleBasedAccessControl);
  }
}(this, function(expect, RoleBasedAccessControl) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RoleBasedAccessControl.Status();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Status', function() {
    it('should create an instance of Status', function() {
      // uncomment below and update the code to test Status
      //var instane = new RoleBasedAccessControl.Status();
      //expect(instance).to.be.a(RoleBasedAccessControl.Status);
    });

    it('should have the property apiVersion (base name: "api_version")', function() {
      // uncomment below and update the code to test the property apiVersion
      //var instane = new RoleBasedAccessControl.Status();
      //expect(instance).to.be();
    });

    it('should have the property commit (base name: "commit")', function() {
      // uncomment below and update the code to test the property commit
      //var instane = new RoleBasedAccessControl.Status();
      //expect(instance).to.be();
    });

    it('should have the property serverAddress (base name: "server_address")', function() {
      // uncomment below and update the code to test the property serverAddress
      //var instane = new RoleBasedAccessControl.Status();
      //expect(instance).to.be();
    });

    it('should have the property platformInfo (base name: "platform_info")', function() {
      // uncomment below and update the code to test the property platformInfo
      //var instane = new RoleBasedAccessControl.Status();
      //expect(instance).to.be();
    });

    it('should have the property pythonVersion (base name: "python_version")', function() {
      // uncomment below and update the code to test the property pythonVersion
      //var instane = new RoleBasedAccessControl.Status();
      //expect(instance).to.be();
    });

    it('should have the property modules (base name: "modules")', function() {
      // uncomment below and update the code to test the property modules
      //var instane = new RoleBasedAccessControl.Status();
      //expect(instance).to.be();
    });

  });

}));
